%YAML:1.0

###### Camera Calibration File For Cam 0 of ZR300 Datasets ######
image_width: 640
image_height: 480
camera_name: cam0
camera_matrix:
  rows: 3
  cols: 3
  data: [608.654, 0.0, 331.215, 0.0, 608.296, 246.375, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data:  [0.0644, -0.114, 0.00127, 0.00203, 0.0]





